# This workflow uses release-please to automate the release process for packages/nuxt-jsonld.
#
# 1. When a commit is pushed to master, it creates a Release PR based on Conventional Commits.
# 2. When the Release PR is merged, release-please automatically:
#    - Updates CHANGELOG.md and package.json
#    - Creates and pushes a new git tag (e.g. v1.4.1)
# 3. The npm-publish workflow is triggered by the tag creation, publishing the package to npm.

name: Create Release PR

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
